name: Build macOS/Linux Binary

on:
  workflow_dispatch:

jobs:
  build-macos-linux:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Load SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPUTYDEV_CORE_ACCESS_KEY }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.15"

      - name: Add github.com to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Build macOS/Linux binary
        run: ./build-macos-linux-binary.sh

      - name: Upload tarball artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-tarball
          path: ./*.tar.gz
